function createellipse(figure1)
%CREATEELLIPSE(FIGURE1)
%  FIGURE1:  annotation figure

%  Auto-generated by MATLAB on 26-Jun-2017 16:32:57

% Create ellipse
annotation(figure1,'ellipse',...
    [0.439970717423133 0.134699853587116 0.134699853587116 0.439970717423133]);

